enable: true
join:
  joinMessage: "%playerName% joined the server!"
  title:
    enabled: true
    title: "&a&lÊ™Éªá´á´á´‡ &6&lÉ´á´‡á´›á´¡á´Ê€á´‹"
    sub: "Welcome!"
  consoleCommands:
    - 'cmi spawn %player_name%'
  playerCommands: []
  motd:
    enabled: true
    delay: 60
    sound: "BLOCK_BEEHIVE_EXIT"
    message:
      - ""
      - "                  &9ğŸŒŠ &6Welcome to Biome Network &9ğŸŒŠ"
      - ""
quit:
  quitMessage: "%playerName% left the server!"

firstJoin:
  broadcast: ""
  sound: "BLOCK_BEEHIVE_EXIT"
  consoleCommands:
    - 'cmi spawn %player_name%'
  playerCommands: []